name: Commit Stage

on: 
  push:
  workflow_dispatch:

env:
  EZCD_DATABASE_URL: ${{ secrets.EZCD_DATABASE_URL }}
  EZCD_PROJECT: demo-project

jobs:
  commit-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ezcd-cli
        uses: ezcdlabs/ezcd@main
        with:
          version: latest

      - name: Commit stage started
        run: ezcd-cli commit-stage-started --project $EZCD_PROJECT --hash "${{ github.sha }}" --author-name "${{ github.actor }}" --author-email "${{ github.actor }}" --message "${{ github.event.head_commit.message }}" --date "${{ github.event.head_commit.timestamp }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run fake tests
        run: ./simulate_stage.sh 20 100 20

      - name: Commit stage completed
        run: ezcd-cli commit-stage-passed --project $EZCD_PROJECT --hash "${{ github.sha }}"

      - name: Trigger Acceptance if there is a queue
        run: |
          QUEUED_HASH=$(ezcd-cli get-queued-for-acceptance --project $EZCD_PROJECT)
          if [ $? -eq 0 ] && [ -n "$QUEUED_HASH" ]; then
            echo "Triggering acceptance stage for commit $QUEUED_HASH"
            gh workflow run 2-acceptance-stage.yml -f commitHash=$QUEUED_HASH
          fi

      - name: Commit stage failed
        if: failure()
        run: ezcd-cli commit-stage-failed --project $EZCD_PROJECT --hash "${{ github.sha }}"